apiVersion: v2
name: it-tools
description: A Helm chart for deploying IT-Tools, a collection of handy online tools for developers and IT professionals
type: application
version: 0.1.0
appVersion: latest